databases:
  - name: ReactWrite
    plan: free
    databaseName: reactwritedb
    user: reactwritedb_owner

services:
  - type: web
    plan: free
    name: ReactWrite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ReactWrite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4